AllCops:
  TargetRubyVersion: 2.5 # purposely an old Ruby version

Layout/LineLength:
  Max: 180

Lint/ConstantDefinitionInBlock:
  Enabled: false

Lint/UnusedBlockArgument:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Naming/MethodParameterName:
  Enabled: false

Style/SafeNavigation:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/RedundantSelf:
  Enabled: false

Style/SingleLineMethods:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: single_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: single_quotes

Style/TrivialAccessors:
  Enabled: false
